// Import all MDI icons used in the application
export {
  mdiArrowLeft,
  mdiAccount,
  mdiPlus,
  mdiAccountOutline,
  mdiBriefcaseOutline,
  mdiAccountGroupOutline,
  mdiCashMultiple,
  mdiCardAccountDetailsOutline,
  mdiCheckCircle,
  mdiChartLineVariant,
  mdiAccountPlus,
  mdiPlay,
  mdiTrashCan,
  mdiMenu,
  mdiInformation,
  mdiCheck,
  mdiWrench,
  mdiNodejs,
  mdiVuejs,
  mdiClose,
  mdiAccountMultiple,
  mdiCardAccountDetails,
  mdiChevronRight,
} from '@mdi/js'
